name: artifact_detection
channels:
  - conda-forge/label/cf202003
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - pandas
  - scikit-learn
  - python=3.9
  - nltk
  - seaborn
  - pygithub
